Xlnc/Controllers/BackupController.cs
using AloFramework.Core.BALs;
using Xlnc.BALs;
using Xlnc.Models;
using Xlnc.Utils;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Configuration;
namespace Xlnc.Controllers
{
    public class BackupController  : Controller
    {
        private log4net.ILog logger = log4net.LogManager.GetLogger(typeof(BackupController));

      
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            try
            {
                logger.Info("inside creating backup");
                var constring = WebConfigurationManager.ConnectionStrings["AloFrameworkContext"].ConnectionString;
                string file = WebConfigurationManager.AppSettings["BackupFilePath"];
                logger.Info("creating backup file in path " + file);
                file += (@"\" + (DateTime.Now.Ticks + ".sql"));
                logger.Info("creating backup file "+ file);
                using (MySqlConnection conn = new MySqlConnection(constring))
                {
                    using (MySqlCommand cmd = new MySqlCommand())
                    {
                        using (MySqlBackup mb = new MySqlBackup(cmd))
                        {
                            cmd.Connection = conn;
                            conn.Open();
                            mb.ExportToFile(file);
                            conn.Close();
                        }
                    }
                }
                Auth.SetStatusMessage(String.Format(Lang.GetLang("backup_saved"), file));
            }
            catch(Exception e) {
                logger.Info("Error in Backup" + e);
            }
            return RedirectToAction("Index");
        }
       
    }
}

Xlnc/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Xlnc.BALs;
using Xlnc.Models;
using System.Text;

namespace Xlnc.Controllers
{
    public class DashboardController : Controller
    {
        private MemberBAL memberBAL = new MemberBAL();
        private ReceiptBAL receiptBAL = new ReceiptBAL();
        private AccountBAL accountBAL = new AccountBAL();
        private log4net.ILog logger = log4net.LogManager.GetLogger(typeof(DashboardController));

        public ActionResult Index(AccountListViewModel accountListViewModel)
        {
            logger.Info("Inside Dashboard");

            accountListViewModel.Accounts = accountBAL.GetIncomeAndExpenseDetails(accountListViewModel);
            return View(accountListViewModel);
        }

        public JsonResult GetDashboardCounts()
        {
            var dasboardCountModel = new DashboardCountModel();
            try
            {
                dasboardCountModel.MembersCount = this.memberBAL.GetMembersCount();
                dasboardCountModel.ReceiptsCount = this.receiptBAL.GetReceiptsListCount();
            }
            catch (Exception ex)
            {
                logger.Error("Problem in retriving dashboard counts, due to " + ex);
            }
            return Json(dasboardCountModel, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetMembersCount()
        {
            int membercount = 0;
            try
            {
                membercount = this.memberBAL.GetMembersCount();
            }
            catch { 
                
            }
            return Json(membercount, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetReceiptsCount()
        {
            List<Receipt> receiptcount = new List<Receipt>();
            try
            {
                receiptcount = this.receiptBAL.GetReceiptsCount();
            }
            catch
            {

            }
            return Json(receiptcount, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetLifeMemberCount()
        {
            int membercount = 0;
            try
            {
                membercount = this.memberBAL.GetLifeMemberCount();
            }
            catch
            {

            }
            return Json(membercount, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetExpiryCount()
        {
            List<Member> expirycount = new List<Member>();
            var totalcount = 0;
            try
            {
                expirycount = this.memberBAL.GetMembersExpiry();
                var count = 0;
                logger.Info("Expiry Count = ");
                foreach (var expiry in expirycount) {
                    //logger.Info("MembershipExpiryDate = " + expiry.MembershipExpiryDate +"Current Date = "+ DateTime.Now.Date.AddDays(+1));
                    if (expiry.MembershipExpiryDate <= DateTime.Now.Date.AddDays(+1)) {
                       
                        count++;
                    }
                }
                totalcount = count;
            }
            catch (Exception e)
            {
                logger.Info("Error in Membership expiry count " + e.Message);
            }
            return Json(totalcount, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetIncomeAndExpenseDetails(AccountListViewModel accountListViewModel)
        { 
          //  List<Account> accountdetails = new List<Account>();
            try{
                accountListViewModel.Accounts = accountBAL.GetIncomeAndExpenseDetails(accountListViewModel);
            }
            catch(Exception e){
                logger.Info("Error in GetIncomeAndExpenseDetails = "+e.Message);
            }

            return View("Index", accountListViewModel);
        }

        public ActionResult IncomeAndExpenseDetailsPrint(string FromDate, string ToDate)
        {
         //   AccountListViewModel accountListViewModel = new AccountListViewModel();
            List<Account> accountdetails = new List<Account>();
            try
            {

                //  accountListViewModel.Accounts = accountBAL.GetIncomeAndExpenseDetails(accountListViewModel);
                accountdetails = this.accountBAL.IncomeAndExpenseDetailsPrint(FromDate, ToDate);
            }
            catch (Exception e)
            {
                logger.Info("Error in GetIncomeAndExpenseDetails = " + e.Message);
            }

            return View("IncomeExpensePrint", accountdetails);
        }
        
    




    }
}

Xlnc/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Xlnc.BALs;
using Xlnc.Models;

namespace Xlnc.Controllers
{
    public class ReportController : Controller
    {
        private AccountBAL accountBAL = new AccountBAL();
        private log4net.ILog logger = log4net.LogManager.GetLogger(typeof(DashboardController));


        public ActionResult Index(AccountListViewModel accountListViewModel)
        {
            accountListViewModel.Accounts = accountBAL.GetGroupByIncomeAndExpenseDetails(accountListViewModel);
            return View(accountListViewModel);
        }

        public ActionResult GetGroupByIncomeAndExpenseDetails(AccountListViewModel accountListViewModel)
        {
            //  List<Account> accountdetails = new List<Account>();
            try
            {
                accountListViewModel.Accounts = accountBAL.GetGroupByIncomeAndExpenseDetails(accountListViewModel);
            }
            catch (Exception e)
            {
                logger.Info("Error in GetIncomeAndExpenseDetails = " + e.Message);
            }

            return View("Index", accountListViewModel);
        }
    }
}

Xlnc/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Xlnc.BALs;
using Xlnc.Models;
using AloFramework.Core.BALs;
using Xlnc.Utils;
using System.Text;
using log4net;
using System.IO;
using System.Net;

namespace Xlnc.Controllers
{
    public class RoomController : Controller
    {

        private RoomBAL roomBAL = new RoomBAL();
        private log4net.ILog logger = log4net.LogManager.GetLogger(typeof(RoomController));

        public ActionResult Index()
        {
            var roomsListViewModel = new RoomsListViewModel();
            roomsListViewModel.Rooms = new List<Room>();
            roomsListViewModel.Rooms = this.roomBAL.GetRooms();
            return View(roomsListViewModel);
        }

        public JsonResult GetAvailableRooms(string filter)
        {
            return Json(this.roomBAL.GetAvailableRooms(filter), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllRooms(string filter)
        {
            return Json(this.roomBAL.GetAllRooms(filter), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetOccupiedRooms(string filter)
        {
            return Json(this.roomBAL.GetOccupiedRooms(filter), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Transfer()
        {
            RoomTransferEditViewModel roomTransferEditModel = new RoomTransferEditViewModel();
            return View(roomTransferEditModel);
        }

        [HttpPost]
        public ActionResult MemberRoomTransfer(RoomTransferEditViewModel roomTransferEditModel)
        {
            this.roomBAL.RoomTransfer(roomTransferEditModel);
            return View("Transfer", roomTransferEditModel);
        }
    }
}

Xlnc/Views/_Shared/_Layout - Copy.cshtml
@using Xlnc.Utils
@{
    Layout = "~/Views/_Shared/_Master.cshtml";
}
<div class="main-content">
  
    <div class="main-header container-fluid">
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8 col-lg-offset-4 ">
                <img src="~/Content/Images/logo.png" class="Receipt_Header" alt="Receipt Header" style="width: 30%;" />
                <div class="center"><b>Women's Hostel</b></div>
            </div>
            <div class="col-lg-2"></div>
        </div>
        <hr />
    </div>
    @{
        var Message = Auth.GetStatusMessage();
        var MessageStatus = Auth.GetMessageStatusType();
        Auth.EmptyStatusMessage();
        if (!String.IsNullOrEmpty(Message) && !String.IsNullOrEmpty(MessageStatus) && MessageStatus == "Warning")
        {
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                @Message
            </div>
        }
        if (!String.IsNullOrEmpty(Message) && String.IsNullOrEmpty(MessageStatus))
        {
            <div class="alert alert-success alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                @Message
            </div>
        }
    }
    @RenderSection("Content")
    @RenderSection("scripts", required: false)
</div>

Xlnc/Views/_Shared/_Master - Copy.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    @RenderPage("~/Views/_Shared/_Scripts.cshtml")
    <!-- Association Manager Base Script> -->
   
</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper" style="background-color:#1c2a33;">
            <ul class="sidebar-nav" style="margin-top:30px;">
                <li class="sidebar-brand">
                    <a href="#">
                        <span class="glyphicon glyphicon-home"></span> XLNC
                    </a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Dashboard/Index") ? "active" : "")">
                    <a  href="@Url.Action("Index", "Dashboard")"><span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span> Dashboard</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Room/Index") ? "active" : "")">
                    <a href="@Url.Action("Index", "Room")"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Room</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Members/Create") ? "active" : "")">
                    <a  href="@Url.Action("Create", "Members")"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Registration</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Members/Index") ? "active" : "")">
                    <a  href="@Url.Action("Index", "Members")"><span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true"></span> Members</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Receipt") ? "active" : "")">
                    <a  href="@Url.Action("Create", "Receipt")"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span> Receipts</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Account/ExpenseIndex") ? "active" : "")">
                    <a  class="list-item" href="@Url.Action("ExpenseCreate", "Account")"><span class="glyphicon glyphicon-collapse-up" aria-hidden="true"></span> Expenses</a>

                </li>
                 <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Account/IncomeIndex") ? "active" : "")">
                    <a  class="list-item" href="@Url.Action("IncomeCreate", "Account")"><span class="glyphicon glyphicon-collapse-down" aria-hidden="true"></span> Income</a>

                </li>
                 @*<li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Insurance") ? "active" : "")">
                    <a href="@Url.Action("Index", "Insurance")"><span class="glyphicon glyphicon-retweet" aria-hidden="true"></span> Insurance</a>

                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Meeting") ? "active" : "")">
                    <a href="@Url.Action("Index", "Meeting")"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> Meeting</a>

                </li>*@
               @*<li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Magazine") ? "active" : "")">
                   <a href="@Url.Action("Index", "Magazine")"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> Xlnc Magazine</a>
               </li>*@
              <!--  <li>
                    <a href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Users</a>
                </li>-->
                @*<li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Sms/SendSms") ? "active" : "")">
                    <a href="@Url.Action("SendSms", "Sms")"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>Send SMS</a>
                </li>*@
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Category") ? "active" : "")">
                    <a href="@Url.Action("Create", "Category")"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>Category</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Report/Index") ? "active" : "")">
                    <a href="@Url.Action("Index", "Report")"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>Reports</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Backup/Create") ? "active" : "")">
                    <a href="@Url.Action("Create", "Backup")"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>Backup</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("User/Logout") ? "active" : "")">
                    <a href="@Url.Action("Logout", "User")"><span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout</a>
                </li>
            </ul>
            
        </div>
        
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="page-content">
                <div class="page-content-container">
                    @RenderBody()
                </div>
            </div>
            <br />
            <div class="footer">
                <p class="text-center">Powered By <a href="http://www.alobin.com" target="_blank">AloBin Technologies</a></p>
            </div>
        </div>

        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Menu Toggle Script -->
    <script>
      /*   $('ul.sidebar-nav li a.list-item').click(function () {
            var url = window.location();
           $('ul.sidebar-nav li a[href="' + url + '"]').parent().addClass('active');
            $(this).toggleClass("active");
            $('ul.sidebar-nav li a').addClass("active");
        });*/
      /* $(function () {
            var pgurl = window.location.href.substr(window.location.href
       .lastIndexOf("/") + 1);
            alert(pgurl);
            $("ul.sidebar-nav li a").each(function () {
                if ($(this).attr("href") == pgurl || $(this).attr("href") == '')
                    $(this).addClass("active");
            })
        });*/
     /*   $('a.list-item').click(function () {
            $('a.list-item').removeClass("active");
            $(this).addClass("active");
        });*/

      /*  $(document).ready(function () {
            $('.sidebar-nav a[href^="/' + location.pathname.split("/")[1]+ '"]').addClass('active');
        });
      */

        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
     
    </script>

</body>

</html>

Xlnc/Views/_Shared/_Master.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    @RenderPage("~/Views/_Shared/_Scripts.cshtml")
    <!-- Association Manager Base Script> -->

</head>

<body>
    <div class="navbar-header">
        <span class="sidebar-menu-toggle">
            <a href="#menu-toggle" class="btn btn-default btn-toggle" id="menu-toggle">
                <!--<span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>-->
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar last"></span>
            </a>
        </span>
        <a href="#" class="navbar-brand visible-xs"><img src="img/logo.png" class="Receipt_Header" alt="Receipt Header" style="width: 20%;" /></a>
    </div>

    <div id="wrapper" class="toggled">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand hidden-xs">
                    <img src="@Url.Content("~/Content/images/logo.png")" class="Receipt_Header" alt="Receipt Header" style="width: 50%;" />
                    <!--<a href="#">
                        <span class="glyphicon glyphicon-home"></span> XLNC
                    </a>-->
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Dashboard/Index") ? "active" : "")">
                    <a href="@Url.Action("Index", "Dashboard")"><span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span> Dashboard</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Room/Index") ? "active" : "")">
                    <a href="@Url.Action("Index", "Room")"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Room</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Members/Create") ? "active" : "")">
                    <a href="@Url.Action("Create", "Members")"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Registration</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Members/Index") ? "active" : "")">
                    <a href="@Url.Action("Index", "Members")"><span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true"></span> Guests</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Receipt") ? "active" : "")">
                    <a href="@Url.Action("Index", "Receipt")"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span> Receipts</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Account/ExpenseIndex") ? "active" : "")">
                    <a class="list-item" href="@Url.Action("ExpenseIndex", "Account")"><span class="glyphicon glyphicon-collapse-up" aria-hidden="true"></span> Expenses</a>

                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Account/IncomeIndex") ? "active" : "")">
                    <a class="list-item" href="@Url.Action("IncomeIndex", "Account")"><span class="glyphicon glyphicon-collapse-down" aria-hidden="true"></span> Income</a>

                </li>
                @*<li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Insurance") ? "active" : "")">
                        <a href="@Url.Action("Index", "Insurance")"><span class="glyphicon glyphicon-retweet" aria-hidden="true"></span> Insurance</a>

                    </li>
                    <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Meeting") ? "active" : "")">
                        <a href="@Url.Action("Index", "Meeting")"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> Meeting</a>

                    </li>*@
                @*<li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Magazine") ? "active" : "")">
                        <a href="@Url.Action("Index", "Magazine")"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> Xlnc Magazine</a>
                    </li>*@
                <!--  <li>
                      <a href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Users</a>
                  </li>-->
                @*<li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Sms/SendSms") ? "active" : "")">
                        <a href="@Url.Action("SendSms", "Sms")"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>Send SMS</a>
                    </li>*@
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Category") ? "active" : "")">
                    <a href="@Url.Action("Index", "Category")"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>Category</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Report/Index") ? "active" : "")">
                    <a href="@Url.Action("Index", "Report")"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>Reports</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Room/Transfer") ? "active" : "")">
                    <a href="@Url.Action("Transfer", "Room")"><span class="glyphicon glyphicon-transfer" aria-hidden="true"></span>Room Transfer</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("Backup/Create") ? "active" : "")">
                    <a href="@Url.Action("Create", "Backup")"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>Backup</a>
                </li>
                <li class="@(HttpContext.Current.Request.Url.AbsolutePath.ToString().Contains("User/Logout") ? "active" : "")">
                    <a href="@Url.Action("Logout", "User")"><span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <nav class="navbar navbar-default navbar-fixed-top hidden-xs">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quick View <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>&nbsp;<span class="glyphicon glyphicon-user">&nbsp;<a href="@Url.Action("Create", "Members")">Register-Create</a></span></li>
                                <li role="separator" class="divider"></li>
                                <li>&nbsp;<span class="glyphicon glyphicon-usd">&nbsp;<a href="@Url.Action("Create", "Receipt")">Receipt-Create</a></span></li>
                                <li role="separator" class="divider"></li>
                                <li>&nbsp;<span class="glyphicon glyphicon-collapse-up">&nbsp;<a href="@Url.Action("ExpenseCreate", "Account")">Expense-Create</a></span></li>
                                <li role="separator" class="divider"></li>
                                <!-- <li role="separator" class="divider"></li> -->
                                <li>&nbsp;<span class="glyphicon glyphicon-collapse-down">&nbsp;<a href="@Url.Action("IncomeCreate", "Account")">Income-Create</a></span></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="@Url.Action("Logout", "User")" title="Logout">
                                Welcome @Session["LoggedUserDisplayName"] <span class="glyphicon glyphicon-off"></span>
                            </a>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="page-content">
                <div class="page-content-container">
                    <div class="container container-custom container-shadow">
                        <div class="box-layout">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="footer">
                <p class="text-center">Powered By <a href="http://www.alobin.com" target="_blank">AloBin Technologies</a></p>
            </div>
        </div>

        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Menu Toggle Script -->
    <script>
        /*   $('ul.sidebar-nav li a.list-item').click(function () {
              var url = window.location();
             $('ul.sidebar-nav li a[href="' + url + '"]').parent().addClass('active');
              $(this).toggleClass("active");
              $('ul.sidebar-nav li a').addClass("active");
          });*/
        /* $(function () {
              var pgurl = window.location.href.substr(window.location.href
         .lastIndexOf("/") + 1);
              alert(pgurl);
              $("ul.sidebar-nav li a").each(function () {
                  if ($(this).attr("href") == pgurl || $(this).attr("href") == '')
                      $(this).addClass("active");
              })
          });*/
        /*   $('a.list-item').click(function () {
               $('a.list-item').removeClass("active");
               $(this).addClass("active");
           });*/

        /*  $(document).ready(function () {
              $('.sidebar-nav a[href^="/' + location.pathname.split("/")[1]+ '"]').addClass('active');
          });
        */

        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

    </script>

</body>

</html>